language: python
python:
  - "3.6"
  - "3.7"

cache: pip

# command to install dependencies
install:
  - pip install -e .

# command to run tests
script:
  - python -m unittest -v tests

jobs:
  include:
    - stage: documentation
      install:
        - pip install -e .
        - pip install sphinx sphinx-rtd-theme
      script:
        - cd docs; make html
      deploy:
        provider: pages
        local_dir: docs/_build/html
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        on:
          branch: master

    - stage: release
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: __token__
        password: "$PYPI_TOKEN"
        on:
          tags: true
